package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
)

const manifestTemplate = `apiVersion: prospect/v1alpha1
kind: App
metadata:
  name: %s
  displayName: "My Awesome App"
  version: 0.1.0
  description: "A short description of what this app does."
  author: "Your Name"
  license: "MIT"
  tags: [security, monitoring]
permissions:
  - "read:events"
inputs: []
dashboards: []
`

func CreateApp(name string) error {
	if _, err := os.Stat(name); !os.IsNotExist(err) {
		return fmt.Errorf("directory '%s' already exists", name)
	}

	// Create directories
	dirs := []string{
		name,
		filepath.Join(name, "dashboards"),
		filepath.Join(name, "inputs"),
		filepath.Join(name, "resources"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
	}

	// Create manifest
	manifestPath := filepath.Join(name, "prospect.yaml")
	manifestContent := fmt.Sprintf(manifestTemplate, name)
	if err := os.WriteFile(manifestPath, []byte(manifestContent), 0644); err != nil {
		return err
	}

	// Create README
	readmePath := filepath.Join(name, "README.md")
	readmeContent := fmt.Sprintf("# %s\n\nGenerated by Prospect CLI\n", name)
	if err := os.WriteFile(readmePath, []byte(readmeContent), 0644); err != nil {
		return err
	}

	return nil
}
